[tool.poetry]
name = "gcn-classic-to-kafka"
version = "0.1.0"
description = "Pump GCN Notices to a Kafka broker"
authors = ["Leo Singer <leo.singer@ligo.org>"]
license = "NOSA"

[tool.poetry.dependencies]
click = "*"
python = "^3.7"
pygcn = "*"
confluent-kafka = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"

[tool.poetry.scripts]
gcn-classic-to-kafka = "gcn_classic_to_kafka.cli:main"

[tool.pytest.ini_options]
asyncio_mode = "strict"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
